version: "3.8"

networks:
  everything:

services:
   #Configure RabbitMQ Container
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: "rabbitmqdemo"
      hostname: "rabbitmqdemo"
      ports:
        - "5672:5672"
        - "15672:15672"
        - "15692:15692"
      networks:
        - "everything"
    #Configure Seq Container
    seq:
      image: datalust/seq:latest
      container_name: "seqdemo"
      hostname: "seqdemo"
      ports:
        - "80:80"
        - "5341:5341"
      deploy:
        resources:
          limits:
            memory: 16G
          reservations:
            memory: 16G
      environment:
        - ACCEPT_EULA=Y
      networks:
        - "everything"
    #Configure Prometheus Container
    prometheus:
      image: prom/prometheus
      container_name: "prometheusdemo"
      hostname: "prometheusdemo"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      networks:
        - "everything"
    #Configure Grafana Container
    grafana:
      image: grafana/grafana-oss
      container_name: "grafanademo"
      hostname: "grafanademo"
      depends_on:
        - prometheus
      volumes:
        - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      ports:
        - "3000:3000"
      networks:
        - "everything"
